# Copyright (c) 2024 The Quranium Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

name: CI
on:
  # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request.
  pull_request:
  # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push.
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  test-each-commit:
    name: 'test each commit'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Determine commit range
        run: |
          sudo apt-get update
          sudo apt-get install clang ccache build-essential libtool autotools-dev automake pkg-config bsdmainutils python3-zmq libevent-dev libboost-dev libsqlite3-dev libdb++-dev systemtap-sdt-dev libminiupnpc-dev libnatpmp-dev qtbase5-dev qttools5-dev qttools5-dev-tools qtwayland5 libqrencode-dev -y
          sudo apt-get update
          sudo apt-get install autoconf
          sudo apt-get install pkg-config
          sudo apt-get install libboost-all-dev
          sudo apt-get install libevent-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev libboost-thread-dev
          sudo apt-get install libdb-dev libdb++-dev
          sudo apt-get install libzmq3-dev
          sudo apt-get install libssl-dev libminiupnpc-dev
      - name: Build
        run: |
          ./autogen.sh 
          CC=clang CXX=clang++ ./configure 
   # make clean && make -j $(nproc) check       ./test/functional/test_runner.py -j $(( $(nproc) * 2 ))

 
